# Generated by Django 4.2.4 on 2023-08-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
